<template>
  <div class="login pt-[280px] pl-[30%] h-[100vh] text-center box-border bg-center bg-no-repeat bg-cover">
    <h1
      class="text-[36px] font-medium absolute left-[17%] top-[40%] bg-gradient-to-r from-[#ecf0f1] to-[#bdc3c7] bg-clip-text text-transparent"
    >
      {{ VITE_GLOB_APP_NAME }}
    </h1>
    <h2 class="bounce-in-top *font-xl mb-[20px] font-medium">登录</h2>
    <el-card shadow="always" class="w-[400px] my-[0] mx-[auto] p-[20px] slide-in-left">
      <el-form ref="formRef" :rules="rules" :model="loginInfo" label-width="80px" size="large">
        <el-form-item label="用户名" prop="username">
          <el-input v-model="loginInfo.username" />
        </el-form-item>
        <el-form-item label="密码" prop="password">
          <el-input v-model="loginInfo.password" type="password" show-password @keyup.enter="handleLoginClick" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" class="w-[100%] mt-[18px]" @click="handleLoginClick">登录</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import type { FormInstance, FormRules } from 'element-plus'
import { useRouter } from 'vue-router'
import useMainStore from '../../store/main'
import { GLOBAL_VARIABLE_NAME } from '@/setting/variable-setting'
import { useGlobSetting } from '@/hooks/setting'
import useStorage from '@/hooks/storage'

const router = useRouter()
const mainStore = useMainStore()
const storage = useStorage()

const { VITE_GLOB_APP_NAME } = useGlobSetting()

const formRef = ref<FormInstance>()
const rules = reactive<FormRules>({
  username: [
    {
      required: true,
      message: '用户名不能为空',
      trigger: 'blur'
    },
    {
      min: 3,
      max: 10,
      message: '用户名长度在3-10位',
      trigger: 'blur'
    }
  ],
  password: [
    {
      required: true,
      message: '密码不能为空',
      trigger: 'blur'
    },
    {
      min: 6,
      max: 12,
      message: '用户名长度在6-12位',
      trigger: 'blur'
    }
  ]
})

const loginInfo = ref({
  username: '',
  password: ''
})

const mockUserName = 'admin'
const mockPassword = '123456'
const mockAccessToken = 'token'
const handleLoginClick = () => {
  formRef.value?.validate((valid) => {
    if (valid) {
      if (loginInfo.value.username === mockUserName && loginInfo.value.password === mockPassword) {
        mainStore.setName(loginInfo.value.username)
        storage.setItem(GLOBAL_VARIABLE_NAME.USERNAME, loginInfo.value.username)
        storage.setItem(GLOBAL_VARIABLE_NAME.TOKEN, mockAccessToken)
        router.push('/main')
      }
    }
  })
}
</script>

<style scoped lang="scss">
.login {
  background-image: url('@/assets/login-bg.jpg');
}
.slide-in-left {
  -webkit-animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
.bounce-in-top {
  -webkit-animation: bounce-in-top 1.1s both;
  animation: bounce-in-top 1.1s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-4-26 11:20:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2022-4-26 11:22:10
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-in-top
 * ----------------------------------------
 */
@-webkit-keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
    transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
    transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
    transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
@keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
    transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
    transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
    transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
</style>
